### ISSUE TITLE
Using long labels increases the distance form the label to the arrow

### ISSUE THREAD

**Issue by StrikeTom** [yishn/tikzcd-editor#24]
When labeling a vertical arrow the text distances itself from the arrow it is attached to.
This issue is relatively new.

**Comment by varkor** [comment]
Illustration:
![image](https://user-images.githubusercontent.com/3943692/40125801-b38f8d32-5923-11e8-92fe-513f4da8eeb2.png)
[Link](https://tikzcd.yichuanshen.de/#eyJub2RlcyI6W3sicG9zaXRpb24iOlswLDBdLCJ2YWx1ZSI6IkEifSx7InBvc2l0aW9uIjpbMCwxXSwidmFsdWUiOiJCIn1dLCJlZGdlcyI6W3siZnJvbSI6MCwidG8iOjEsImxhYmVsUG9zaXRpb24iOiJyaWdodCIsInZhbHVlIjoiZmZmZmZmZmZmZmZmIn1dfQ==)

**Comment by yishn** [comment]
Good catch everyone! @Isomorphisme Do you have any idea what's going on? Otherwise, I will take a look this weekend.

**Comment by Isomorphisme** [comment]
Ups, it seems I broke something in the process. I quickly checked and it appears that getting rid of the 'heightDiff' parts fixes the problem. To be honest, I did not really understand this parameter but it looked like it was not doing anything.

**Comment by Isomorphisme** [comment]
I think I broke something because I don't understand what the 'heightDiff' is. It seems that deleting this little part solves the issue though. I do not have a lot of time to test, but if someone wants, I think that something along the lines of https://github.com/Isomorphisme/tikzcd-editor/commit/52b6c7e81ddb4ac0fcb14742c1bd5943d0b45e69 should work.

**Comment by yishn** [comment]
Took me a while to figure out what I wrote, but I think I finally got the correct computations... 😅
