### ISSUE TITLE
Double-struck arrows?

### ISSUE THREAD

**Issue by Karl-D-Asmussen** [yishn/tikzcd-editor#6]
It would be pretty cool with the ability to make arrows between arrows (for natural transformations, etc.)

Double-struck arrows too (which could double as equals-signs without an arrowhead.)

**Comment by yishn** [comment]
Do you have some working example tikzcd code for diagrams with arrows between arrows? I fear these diagrams might be too complicated. Double struck arrows would be cool.

**Comment by yishn** [comment]
tikz-cd only supports double struck arrows with a limited combination of arrow heads and tails. I'm not sure how we should handle these.

**Comment by Karl-D-Asmussen** [comment]
Maybe make a selection of 'special arrows' for double-struck and equals? Otherwise, one can define one's own arrow styles with relative ease in tikz.

    \begin{tikzcd}
    C \arrow[r, bend right=49, ""{name=a1}] \arrow[r, bend left=49, ""{name=a2}] & D
    \arrow[from=a1,to=a2,=>]
    \end{tikzcd}

I do believe the above will do it.

**Comment by yishn** [comment]
Currently, the logic behind tikzcd-editor only allows arrows between grid cells. Everything depends on that, the drawing algorithm, the code generator, the app state. Implementing arrow between arrows is out of scope of this project since it requires rewriting everything from scratch. That said, I'll keep this issue open for double-struck arrows.
